# ============================================================ 
# Device specifics
# ============================================================ 
substitutions:
  name: esp32-thz504
  friendly_name: ESP32-THZ-Controller
  display_name: ESP32-THZ-Controller
  api_key: !secret esp32-thz504_api_enc
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fallback: !secret wifi_fallback
  ota_password: !secret ota

# ============================================================ 
# include base config
# ============================================================ 
packages:
  esp_base: !include common/esp_base.yaml
  thz504: !include local_code/thz/yaml/thz504.yaml

# ============================================================ 
# Default ESP config
# ============================================================ 
esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf

esphome:
  platformio_options:
    build_flags:
      - "-std=gnu++2a"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"
  on_boot:
    priority: -100
    then:
      # Boot indication - Blue
      - light.turn_on:
          id: status_rgb_led
          brightness: 50%
          red: 0%
          green: 0%
          blue: 100%
      - delay: 3s

# Enable logging
logger:
  level: INFO     #Default Operation
  #level: DEBUG   #Troubleshooting
  #level: VERBOSE #Troubleshooting

# ============================================================ 
# Device config
# ============================================================ 

# Substitutions are inherited from common.yaml
# Time configuration is inherited from common.yaml
# CAN configuration is inherited from common.yaml

# Enable build-in Webserver
web_server:
  port: 80
  
# RGB Status LED - Simple status indicator
light:
  - platform: esp32_rmt_led_strip
    pin: GPIO8
    num_leds: 1
    id: status_rgb_led
    name: "Status LED"
    chipset: WS2812
    rgb_order: RGB
 
 # Status LED Automation - Visual system status
interval:
  - interval: 3s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            # WiFi connected - Solid Green (ready for CAN bus)
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 0%
                green: 100%
                blue: 0%
          else:
            # WiFi disconnected - Solid Red
            - light.turn_on:
                id: status_rgb_led
                brightness: 30%
                red: 100%
                green: 0%
                blue: 0%

# ============================================================ 
# Sensors
# ============================================================ 
# System monitoring sensors
sensor:
# internal Temperature
  - platform: internal_temperature
    name: ESP Internal Temperature
    id: esp_internal_temperature
    unit_of_measurement: '°C'
    update_interval: 60s
    entity_category: diagnostic
